[greeter]
background = /usr/share/backgrounds/gardevoir/wallpaper-4k.png
theme-name = Adwaita-dark
icon-theme-name = Papirus-Dark
font-name = DejaVu Sans 11
active-monitor = DP-0
position = 50%,center -0;50% 50%
round-user-image = true
indicators = ~host;~spacer;~clock;~spacer;~power
clock-format = %H:%M
